#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="((?<!([A-Za-z]{1,10})-?)[A-Z]+-\d+)"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "The commit message must contain a JIRA issue identifier in the format XXX-9999"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
