#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# See https://betterprogramming.pub/how-to-automatically-add-the-ticket-number-in-git-commit-message-bda5426ded05 for implementation details

# The input is a file containing the commit message.
file=$1
commit_message=$(cat $file)

# Use git rev-parse to find the current branch and send the full branch through grep to parse out the Jira identifier
issue_identifier=[$(git rev-parse --abbrev-ref HEAD | grep -Eo '^(\w+/)?(\w+[-_])?[0-9]+' | grep -Eo '(\w+[-])?[0-9]+' | tr "[:lower:]" "[:upper:]")]

# If there was no identifier found, or the message already contains it, exit
if [[ $issue_identifier == "[]" || "$commit_message" == "$issue_identifier"* ]];
then
  exit 0;
fi

# Otherwise, add the ticket to the existing message and send it back to the file.
echo "$issue_identifier $commit_message" > $file